### ISSUE TITLE
DDS format to save

### ISSUE THREAD

**Issue by rhadamants** [lehieugch68/PJ5-Font-Extractor#1]
I know it is annoying to be asked about something that is in progress.
I edited a dds image but I don't know the correct compression to save. I tried a few, but the character didn't appear in the game.

**Comment by lehieugch68** [comment]
**L8 format** (8 bits per pixel, luminance: 8).

To add a new character:
- Save the DDS file in **L8 format** to the **IndexedPixelData/Import** folder.
- Add glyph information to the **glyphs.txt** file.

Note: ImageWidth must be divisible by 2.

**Comment by rhadamants** [comment]
Add a new glyph or replace an existing one?
Nvidia texture tool have this L8 format?
I cannot look at it right now.

**Comment by lehieugch68** [comment]
Add a new one, or overwrite the existing one if you want to replace it.

Save with Nvidia Texture Tool: [L8 Format](https://imgur.com/a/s5u0kNx)

**Comment by rhadamants** [comment]
I was successful in editing it and it showed up in the game.

But it got a different color tone.
![Captura de tela 2021-11-04 144809](https://user-images.githubusercontent.com/9261306/140393404-7ddc595b-3ef4-4dec-8b7f-17eef6bb36a9.png)
Character: ã

I edited the image by opening transparency as alpha channel.
Do you know what font is used in the game?

**Comment by rhadamants** [comment]
Did you create the missing characters?
Couldn't find a similar .ttf to use?

**Comment by lehieugch68** [comment]
Yeah, but I simply added accents for the missing characters, I didn't replace with another TTF font.
Here is my working directory if you are interested (full Vietnamese characters): [Font_default.zip](https://github.com/lehieugch68/PJ5-Font-Extractor/files/7477400/Font_default.zip)

**Comment by rhadamants** [comment]
Do you plan to create something to extract textures?
Like the layout directory.

New Game and some text seems to be in textures.

**Comment by lehieugch68** [comment]
I haven't figured out the structure of the KSCL files containing the textures yet, but I don't care about them. Since editing the texture doesn't change the size of the file, so I just export the raw data manually.

Take the **title_layout_eu.kscl** file as an example:
```
0x398E: 4 bytes (total files)
0x4339: Data of files:
- 4 bytes: Format type (3: DXT5, 0: R8G8B8A8)
- 2 bytes: Image width
- 2 bytes: Image height
- Skip 20 bytes (maybe this is the mark for RGBA channels)
- 4 bytes: Image data length
- Skip 40 bytes
- Image data (headerless)
...
```
Add DDS headers for each image data, for example: [title_layout_eu.kscl-DXT5-700-64-394937.zip](https://github.com/lehieugch68/PJ5-Font-Extractor/files/7490843/title_layout_eu.kscl-DXT5-700-64-394937.zip)

In-game:
![20211106225733_1](https://user-images.githubusercontent.com/51288927/140616591-1b257b5d-89c8-4a7d-8e64-47d10f24b4b5.jpg)

**Comment by rhadamants** [comment]
Can you please share your directory with these psd images?

Inserting the data without a header for me should be possible.

I did it with FFX steam before I had a tool for the phyre files.
And then I found another tool that extracted the header from the phyre file into a file and copied the data from the dds to another file with the dds header. All this by hard code.

It worked only by copying the data into existing headers.

**Comment by lehieugch68** [comment]
I haven't been doing much, you should do the same thing with the rest of the files as I instructed: [title_layout_eu_export.zip](https://github.com/lehieugch68/PJ5-Font-Extractor/files/7490890/title_layout_eu_export.zip)

Also, saving as PSD doesn't make sense because we have to edit the Alpha channel (I don't know if there is another way to do this).

**Comment by rhadamants** [comment]
Some images have complex effects in the alpha channel.
I open the image as transparency in these cases and edit it.
I save the format and the alpha channel is generated automatically when I save the image.

This way I don't have to edit the alpha channel individually.
I have done this with several FF13 images. Like those images that appeared on the screen with the name of the location when you arrived at a new location for the first time.

**Comment by rhadamants** [comment]
This noesis help?
[fmt_g1m.zip](https://github.com/lehieugch68/PJ5-Font-Extractor/files/7492750/fmt_g1m.zip)

open kslt but not kscl

**Comment by lehieugch68** [comment]
KSCL files contain KSLT file, use Hex Editor delete from beginning of KSCL file to TLSK3100 string, you will get KSLT file.

**Comment by rhadamants** [comment]
It works.

Noesis only exports. Is there a tool to import?
With this plugin can you create a tool to import and export?

**Comment by lehieugch68** [comment]
Yeah, I'll do that when I have time.

**Comment by lehieugch68** [comment]
https://github.com/lehieugch68/PJ5-KSCL-Unpacker

**Comment by JinYushiyuu** [comment]
@lehieugch68 dude, do you have any tips for adding special characters in the .dds file of the game atelier ryza ever darkness & the secret hideout?

**Comment by lehieugch68** [comment]
> @lehieugch68 dude, do you have any tips for adding special characters in the .dds file of the game atelier ryza ever darkness & the secret hideout?

Send me sample files (.g1n)

**Comment by JinYushiyuu** [comment]
![image](https://github.com/lehieugch68/PJ5-Font-Extractor/assets/53840954/34b49cfe-42d5-4de9-b94b-ead8c178eca9)

@lehieugch68 

here is a sample print of the .dds file that resides inside mainfont01_hd1080_0.g1t.

My situation is sad, I've been trying for days and I don't get results for adding letters with special Portuguese characters, but it seems that the .dds is mapped

I'm going to send you the extracted file so you can have a look, I've tried everything but I can't, if you can help me I'll be very grateful

[font.zip](https://github.com/lehieugch68/PJ5-Font-Extractor/files/11963532/font.zip)

**Comment by lehieugch68** [comment]
They are texture files, are there any other files in the game's font directory?
